# Form implementation generated from reading ui file 'giaodien.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 300)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.txtName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtName.setObjectName("txtName")
        self.verticalLayout.addWidget(self.txtName)
        self.btnSayHello = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSayHello.setObjectName("btnSayHello")
        self.verticalLayout.addWidget(self.btnSayHello)
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setObjectName("lblResult")
        self.verticalLayout.addWidget(self.lblResult)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo PyQt6 + Qt Designer"))
        self.labelTitle.setText(_translate("MainWindow", "Nhap ten cua ban:"))
        self.txtName.setPlaceholderText(_translate("MainWindow", "Vi du: Hoan"))
        self.btnSayHello.setText(_translate("MainWindow", "Chao"))
        self.lblResult.setText(_translate("MainWindow", "Ket qua se hien thi o day"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
